spring:
  http:
    multipart:
      maxFileSize: 50Mb
      maxRequestSize: 50Mb

  datasource:                           # 指定数据源
    platform: mysql                        # 指定数据源类型
    #    primary:
    driverClassName: com.mysql.cj.jdbc.Driver
    show_sql: true
    #   数据库连接配置
    url: jdbc:mysql://94.191.61.73:3306/couple_home?useUnicode=true&characterEncoding=utf-8&useSSL=true
    username: root
    password: 123456
    type: com.alibaba.druid.pool.DruidDataSource

    maxActive: 50   #最大的活跃连接数
    maxIdle: 50     #最大空闲连接数
    minIdle: 20       #最小空闲连接数
    initialSize: 20     #初始连接数
    testWhileIdle: true    #验证连接的有效性
    #validationQuery: select 1 from dual   #连接有效性检查语句
    validationQuery: select 1
    #指明是否在从池中取出连接前进行检验,如果检验失败,则从池中去除连接并尝试取出另一个
    testOnBorrow: true
    #指明是否在归还到池中前进行检验
    testOnReturn: false
    #配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
    # timeBetweenEvictionRunsMillis: 60000
    removeAbandoned: true   #剔除removeAbandonedTimeout内仍然在用的连接，为的是防止连接泄漏
    removeAbandonedTimeout: 36000 #1分钟，如果业务真有长时间操作必须放大
    logAbandoned: true
